### ISSUE TITLE
./audiohost segfaults on Linux x86_64

### ISSUE THREAD

**Issue by Lucretia** [steinbergmedia/vst3sdk#22]
I get the following backtrace in gdb:

```bash
(gdb) set args ~/opt/REAPER/Plugins/FX/reafir.vst.so
(gdb) r
Starting program: /tmp/vst3sdk/build/bin/Debug/audiohost ~/opt/REAPER/Plugins/FX/reafir.vst.so
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555556815c in Steinberg::IPtr<Steinberg::IPluginFactory>::IPtr (this=0x7fffffffd1b8, other=...) at /tmp/vst3sdk/pluginterfaces/base/smartpointer.h:125
125     inline IPtr<I>::IPtr (const IPtr<I>& other) : ptr (other.ptr)
(gdb) bt
#0  0x000055555556815c in Steinberg::IPtr<Steinberg::IPluginFactory>::IPtr (this=0x7fffffffd1b8, other=...) at /tmp/vst3sdk/pluginterfaces/base/smartpointer.h:125
#1  0x0000555555567539 in VST3::Hosting::PluginFactory::PluginFactory (this=0x7fffffffd1b8) at /tmp/vst3sdk/public.sdk/source/vst/hosting/module.h:130
#2  0x0000555555566561 in Steinberg::Vst::AudioHost::App::startAudioClient (this=0x5555557f4bf0, path="/home/laguest/opt/REAPER/Plugins/FX/reafir.vst.so", effectID=..., flags=0)
    at /tmp/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/audiohost.cpp:84
#3  0x0000555555566bbe in Steinberg::Vst::AudioHost::App::init (this=0x5555557f4bf0, cmdArgs=std::vector of length 1, capacity 1 = {...})
    at /tmp/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/audiohost.cpp:133
#4  0x0000555555566c9a in main (argc=2, argv=0x7fffffffd588) at /tmp/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/audiohost.cpp:164
```

Doesn't matter what I pass, it does this.

**Comment by scheffle** [comment]
Audiohost can only host vst3 plug-ins. I agree it should not segfault when you load something else into it. We will fix this in the next update.

**Comment by Lucretia** [comment]
I don't even remember reporting this, it's that old. 2 year turnaround, fuck me!
