### ISSUE TITLE
ASAN issue with editor

### ISSUE THREAD

**Issue by abique** [steinbergmedia/vst3sdk#6]
```
=================================================================
==16320==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x607000076760 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   72 bytes;
  size of the deallocated type: 48 bytes.
Diva VST3 telling Unknown host about latency change, host should request number of latency samples next
    #0 0x7fba8d422b51 in operator delete(void*, unsigned long) /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_new_delete.cc:140
    #1 0x7fba89e62d2a in Gtk::Container::foreach(sigc::slot<void, Gtk::Widget&, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil> const&) (/usr/lib/libgtkmm-3.0.so.1+0x316d2a)
    #2 0x7fba89e62eb5 in Gtk::Container::show_all_children(bool) (/usr/lib/libgtkmm-3.0.so.1+0x316eb5)
    #3 0x55a07f86e54c in Steinberg::Vst::EditorHost::WindowGtk::WindowGtk() ../public.sdk/samples/vst-hosting/editorhost/source/platform/linux/window.cpp:84
    #4 0x55a07f86d85d in Steinberg::Vst::EditorHost::X11Window::Impl::Impl(Steinberg::Vst::EditorHost::X11Window*) ../public.sdk/samples/vst-hosting/editorhost/source/platform/linux/window.cpp:343
    #5 0x55a07f86d535 in Steinberg::Vst::EditorHost::X11Window::X11Window() ../public.sdk/samples/vst-hosting/editorhost/source/platform/linux/window.cpp:266
    #6 0x55a07f873921 in void __gnu_cxx::new_allocator<Steinberg::Vst::EditorHost::X11Window>::construct<Steinberg::Vst::EditorHost::X11Window>(Steinberg::Vst::EditorHost::X11Window*) /usr/include/c++/7.2.0/ext/new_allocator.h:136
    #7 0x55a07f8734ce in void std::allocator_traits<std::allocator<Steinberg::Vst::EditorHost::X11Window> >::construct<Steinberg::Vst::EditorHost::X11Window>(std::allocator<Steinberg::Vst::EditorHost::X11Window>&, Steinberg::Vst::EditorHost::X11Window*) /usr/include/c++/7.2.0/bits/alloc_traits.h:475
    #8 0x55a07f872d03 in std::_Sp_counted_ptr_inplace<Steinberg::Vst::EditorHost::X11Window, std::allocator<Steinberg::Vst::EditorHost::X11Window>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<>(std::allocator<Steinberg::Vst::EditorHost::X11Window>) /usr/include/c++/7.2.0/bits/shared_ptr_base.h:526
    #9 0x55a07f871f12 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Steinberg::Vst::EditorHost::X11Window, std::allocator<Steinberg::Vst::EditorHost::X11Window>>(std::_Sp_make_shared_tag, Steinberg::Vst::EditorHost::X11Window*, std::allocator<Steinberg::Vst::EditorHost::X11Window> const&) /usr/include/c++/7.2.0/bits/shared_ptr_base.h:637
    #10 0x55a07f870d6f in std::__shared_ptr<Steinberg::Vst::EditorHost::X11Window, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Steinberg::Vst::EditorHost::X11Window>>(std::_Sp_make_shared_tag, std::allocator<Steinberg::Vst::EditorHost::X11Window> const&) /usr/include/c++/7.2.0/bits/shared_ptr_base.h:1295
    #11 0x55a07f8702a7 in std::shared_ptr<Steinberg::Vst::EditorHost::X11Window>::shared_ptr<std::allocator<Steinberg::Vst::EditorHost::X11Window>>(std::_Sp_make_shared_tag, std::allocator<Steinberg::Vst::EditorHost::X11Window> const&) /usr/include/c++/7.2.0/bits/shared_ptr.h:344
    #12 0x55a07f86f8af in std::shared_ptr<Steinberg::Vst::EditorHost::X11Window> std::allocate_shared<Steinberg::Vst::EditorHost::X11Window, std::allocator<Steinberg::Vst::EditorHost::X11Window>>(std::allocator<Steinberg::Vst::EditorHost::X11Window> const&) /usr/include/c++/7.2.0/bits/shared_ptr.h:691
    #13 0x55a07f86f00b in std::shared_ptr<Steinberg::Vst::EditorHost::X11Window> std::make_shared<Steinberg::Vst::EditorHost::X11Window>() /usr/include/c++/7.2.0/bits/shared_ptr.h:707
    #14 0x55a07f86d422 in Steinberg::Vst::EditorHost::X11Window::make(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Steinberg::Vst::EditorHost::Size, bool, std::shared_ptr<Steinberg::Vst::EditorHost::IWindowController> const&, _XDisplay*, std::function<void (Steinberg::Vst::EditorHost::X11Window*)> const&) ../public.sdk/samples/vst-hosting/editorhost/source/platform/linux/window.cpp:255
    #15 0x55a07f8612fa in Steinberg::Vst::EditorHost::Platform::createWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Steinberg::Vst::EditorHost::Size, bool, std::shared_ptr<Steinberg::Vst::EditorHost::IWindowController> const&) ../public.sdk/samples/vst-hosting/editorhost/source/platform/linux/platform.cpp:127
    #16 0x55a07f84bf59 in Steinberg::Vst::EditorHost::App::createViewAndShow(Steinberg::Vst::IEditController*) ../public.sdk/samples/vst-hosting/editorhost/source/editorhost.cpp:213
    #17 0x55a07f84bba5 in Steinberg::Vst::EditorHost::App::openEditor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, VST3::Optional<VST3::UID>, unsigned int) ../public.sdk/samples/vst-hosting/editorhost/source/editorhost.cpp:187
    #18 0x55a07f84c3c6 in Steinberg::Vst::EditorHost::App::init(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ../public.sdk/samples/vst-hosting/editorhost/source/editorhost.cpp:262
    #19 0x55a07f86166d in Steinberg::Vst::EditorHost::Platform::run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ../public.sdk/samples/vst-hosting/editorhost/source/platform/linux/platform.cpp:185
    #20 0x55a07f8618fc in main ../public.sdk/samples/vst-hosting/editorhost/source/platform/linux/platform.cpp:251
    #21 0x7fba87da1f69 in __libc_start_main (/usr/lib/libc.so.6+0x20f69)
    #22 0x55a07f84aad9 in _start (/home/abique/develop/vst3sdk/build/bin/editorhost+0x1bad9)

0x607000076760 is located 0 bytes inside of 72-byte region [0x607000076760,0x6070000767a8)
allocated by thread T0 here:
    #0 0x7fba8d421489 in operator new(unsigned long) /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_new_delete.cc:80
    #1 0x7fba89e63e21 in sigc::internal::typed_slot_rep<sigc::mem_functor0<void, Gtk::Widget> >::dup(void*) (/usr/lib/libgtkmm-3.0.so.1+0x317e21)

SUMMARY: AddressSanitizer: new-delete-type-mismatch /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_new_delete.cc:140 in operator delete(void*, unsigned long)
==16320==HINT: if you don't care about these errors you may set ASAN_OPTIONS=new_delete_type_mismatch=0
==16320==ABORTING
Aborted (core dumped)
```

**Comment by scheffle** [comment]
Looks like an issue of gtkmm not the sdk.
